version: "3.5"
services:
  orca-mongo:
    restart: "no"
    logging:
      driver: "none"
    ports:
      - "27017:27017"
  orca-api:
    restart: "no"
    command: [ "npm run start:dev"]
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/share/app
      - /usr/share/app/node_modules
